### ISSUE TITLE
DB type?

### ISSUE THREAD

**Issue by YanshuoH** [mrstrlc-yipeng/motelo#11]
What's your type of db?

I've used Logstash + ElasticSearch for log monitoring in fr tv, hope it'll help.

**Comment by phamour** [comment]
easy sqlite for now...
i ve never heard about these. in fact this is a fast version with php and i
d like to transfer it to pure node webkit app using something like
localStorage of backbone. i ll check what you mentioned thx!

**Comment by YanshuoH** [comment]
It is used for monitoring massive log. ElasticSearch is a kind of DB engine. But for a simple version (webkit after all)...hmmmmm

Okkk, I thought it's something about Big data

**Comment by phamour** [comment]
it has nothing about big data although it could have a big amount of data in the future, since i ll fill in with all test results of my 3 years...
on the other hand, i pretty doubt about the techno, web or desktop. this web version may just be a quick presentation for others to see this thing as my personal project...

**Comment by YanshuoH** [comment]
It may depend on the kind of presentation you want. If you give 50M data to any Web Navigator, it is potentially fucked up (may not with your AlienWare lol).
Though...desktop is not easy to develop. It depends.
